
spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri: http://11.11.136.131/jiyanlong/conf-repo.git
          username: jiyanlong                                           # gitlab仓库的账号
          password: jyl7876442
          searchPaths: config-repo
  rabbitmq:
    host: 11.11.136.141
    port: 5672
    username: guest
    password: guest
  profiles:
    active: dev
#spring.cloud.config.server.git.searchPaths: config-repo
security:
  user:
    name: user
    password: password



---
spring:
  profiles: dev
server:
  port: 8888

---
spring:
  profiles: ocp
server:
  port: 8080