server:
  port: 0
spring:
  application:
    name: svca-service
  profiles:
    active: dev
  sleuth:
    integration:
      enabled: false
    scheduled:
      skip-pattern: "^org.*HystrixStreamTask$"
    sampler:
      percentage: 1
  rabbitmq:
    host: 11.11.136.141
    port: 5672
    username: guest
    password: guest
    listener:
      simple:
        concurrency: 2
        max-concurrency: 2
  cloud:
    stream:
      bindings:
        sleuth:
          destination: sleuth-jyl
name: 小明

management:
  security:
    enabled: false
  health:
      rabbit:
        enabled: false
feign:
  hystrix:
    enabled: true
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000
  stream:
    queue:
      destination: hystrix-jyl
svcb-service:
  ribbon:
    ReadTimeout: 3000
    ConnectTimeout: 2000
    MaxAutoRetriesNextServer: 3
#    OkToRetryOnAllOperations: true
eureka:
  instance:
    instance-id: ${spring.cloud.client.hostname}:${spring.application.name}:${spring.application.instance_id:${server.port}}:${random.int[0,999]}
#    health-check-url-path: ${server.context-path}${management.context-path}/health
#    status-page-url-path: ${server.context-path}${management.context-path}/info
    hostname: 127.0.0.1
    prefer-ip-address: true
    metadata-map:
      user.name: ${security.user.name}
      user.password: ${security.user.password}
#      management.context-path: ${server.context-path}${management.context-path}
  client:
    service-url:
      defaultZone: http://user:${REGISTRY_SERVER_PASSWORD:password}@${SPRING_CLOUD_EUREKA_URI:127.0.0.1:8761}/eureka/
#svcb-service:
#  ribbon:
##    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule

---
spring:
  profiles: ocp
server:
  port: 8080

