logging:
  level:
    org.springframework.cloud.netflix.zuul.filters.post.SendErrorFilter: error

turbine:
  stream:
    port: 8041
    destination: ${TURBINE_STREAM_DESTINATION:hystrix-jyl}
#  combine-host-port: true



eureka:
  instance:
    hostname: 127.0.0.1
    prefer-ip-address: true
  client:
    service-url:
#      defaultZone: http://admin:dev1234@test-cnpc-dj-commonservice-eureka-ha2-feature-zj-dev-dj-cnpc.apps.jtdjdev.cnpc/eureka/,http://admin:dev1234@test-cnpc-dj-commonservice-eureka-ha2-feature-zj-dev-dj-cnpc.apps.jtdjdev.cnpc/eureka/
      defaultZone: http://user:password@127.0.0.1:8761/eureka/

spring:
  application:
    name: monitor
  profiles:
    active: dev
  rabbitmq:
    host: 11.11.136.141
    port: 5672
    username: guest
    password: guest
  boot:
    admin:
      routes:
        endpoints: env,metrics,trace,dump,jolokia,info,configprops,trace,logfile,refresh,flyway,liquibase,heapdump,loggers,auditevents,hystrix.stream
      turbine:
        clusters: default
        location: http://127.0.0.1:${turbine.stream.port}
        enabled: true

security:
  user:
    name: admin
    password: ${MONITOR_SERVER_PASSWORD:admin}
    
---
spring:
  profiles: ocp
server:
  port: 8080

---
spring:
  profiles: dev
server:
  port: 8040
